### ISSUE TITLE
Send an intro email to the team

### ISSUE THREAD

**Issue by nobuti** [Zityhub/Onboarding-luisa#3]
Introduce yourself by sharing a bit of your background. Tell us about yourself, and don't forget to mention your favorite food, that tv show you are watching these days or your most-liked restaurant in Madrid.

### How to test it
- [x] Add a PR to include in the readme file a copy of your email, and replies. Don't worry if you need to create a few PR.

**Comment by luisapenalosa** [comment]
I’m Luisa and I'm very exited to be your new teammate as designer! I´m going to talk a little about my background.

I studied Fine Arts some years ago and I’ve always worked in advertising as Art Director and creative designer, until more than two years ago I decided to change of sector and get into the product design. Since then, I’ve been working at zara.com as a UX designer until today, that I start working with you!

Finishing with my issues:

Favorite meal: Chip potatoes (have to stop it, I know)
Favorite TV show: The twins who renovate houses, amazing! :D
Favorite restaurant in Madrid: Pending task! I’m been living in Coruña for the last year, if you go there, you have to go to Betanzos to taste la tortilla de patatas. 

Thank you all, and sorry for my english :D
